name: Publish @faire/ts-unused-class-members

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn ts:run scripts/publishIfBumped.ts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          VERDACCIO_TOKEN: ${{ secrets.FAIRE_CI_VERDACCIO_TOKEN }}
